import { Inter } from 'next/font/google'
import '@app/custom-pico.scss'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='container-fluid'>
          <nav>
            <ul>
              <li><strong>{`Jacob's Poker Utils Web App`}</strong></li>
            </ul>
            <ul>
              <li>
                <Link href='/home-game-calculator'>Home Game Calculator</Link>
              </li>
            </ul>
          </nav>
          {children}
        </div>
      </body>
    </html>
  )
}
