import { Inter } from 'next/font/google'
import '@app/custom-pico.scss'
import Link from 'next/link'
import { Analytics } from '@vercel/analytics/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: `Jacob's Poker Utilities`,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='container-fluid'>
          <header>
            <nav>
              <ul>
                <li><strong>{`Jacob's Poker Utils Web App`}</strong></li>
              </ul>
              <ul>
                <li>
                  <Link href='/home-game-calculator'>Home Game Calculator</Link>
                </li>
              </ul>
            </nav>
          </header>
          <main>
            {children}
            <Analytics />
          </main>
          <footer>
            <small>
              Built by <a href='https://www.linkedin.com/in/jacob-lipton/' target='_blank'>Jacob Lipton</a>
              {` • `}
              <a href="https://github.com/jlipton04/preflop-webapp" target='_blank'>Source code</a></small>
          </footer>
        </div>
      </body>
    </html>
  )
}
